const blogs = [
    {
        id: '1',
        slug:'Automatically',
        title: 'We automatically search for andapply coupons when.',
        screens:'/images/blog/img-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem beatae errodio.',
        author: 'Jenefer Willy',
        authorTitle:'Farmer',
        authorImg:'/images/blog/blog-avater/img-1.jpg',
        create_at: '14 AUG,21',
        blogSingleImg:'/images/blog/img-5.jpg', 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        slug:'traffic',
        title: 'How to get more traffic in your website of ecommerce.',
        screens: '/images/blog/img-2.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem beatae errodio.',
        author: 'Konal Biry',
        authorTitle:'Farmer',
        authorImg:'/images/blog/blog-avater/img-2.jpg',
        create_at: '16 AUG,21',
        blogSingleImg:'/images/blog/img-6.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
    {
        id: '3',
        slug:'Rules',
        title: '25 Rules and regulation to be successful in your business.',
        screens: '/images/blog/img-3.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem beatae errodio.',
        author: 'Jenefer Willy',
        authorTitle:'Farmer',
        authorImg:'/images/blog/blog-avater/img-3.jpg',
        create_at: '18 AUG,21',
        blogSingleImg:'/images/blog/img-7.jpg',
        comment:'95',
        blClass:'format-video',
    },
];
export default blogs;